# headers and icon 
title: Caden Smith
info: BS in EE @ TAMU
icon-pic: assets/img/"Gigem 1000x1000.png"

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
